mystek/npc/urls.py
from django.conf.urls import url

from . import views

app_name = 'npc'

urlpatterns = [
	# NPC CLUSTER
    # https://mystek.com/npc/
    url(r'^$', views.npc_list, name = 'npc_list'),
    # https://mystek.com/npc/<uid>/
    url(r'^(?P<uid>0x[0-9A-F]+)/$', views.npc_detail, name = 'npc_detail'),
    # https://mystek.com/npc/<uid>/
    url(r'^create/$', views.npc_create, name = 'npc_create'),
    # https://mystek.com/npc/edit/<uid>
    url(r'^edit/(?P<uid>0x[0-9A-F]+)/$', views.npc_edit, name = 'npc_edit'),
    url(r'^help/$', views.npc_help, name = 'npc_help'),
]

mystek/npc/models.py
from django.db import models

# Create your models here.

mystek/npc/forms.py
from django.forms import ModelForm

from registry.models import NPC


class NPCForm(ModelForm):
	class Meta:
		model = NPC
		fields = [
			'name',
			'character_id',
			'abst_world',
			'description',
			'character_dialog',
			'reward_items',
			'reward_items_trigger',
		]

mystek/npc/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import NPCForm

from registry.models import NPC

# Create your views here.
#####################
# CLUSTER 5: NPC
#####################
@login_required
def npc_list(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	item_list = NPC.objects.all()
	paginator = Paginator(item_list, 30) # show 30 item listings at once

	page = request.GET.get('page')
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		# if page is not an integer, deliver first page
		items = paginator.page(1)
	except EmptyPage:
		# if page is out of range, deliver last page of results
		items = paginator.page(paginator.num_pages)

	context['objects_list'] = items

	return render(request, 'npc/npc-list.html', context)

@login_required
def npc_help(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.add_npc'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	return render(request, 'npc/npc-help.html', context)

@login_required
def npc_detail(request, uid):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL

	context['item'] = NPC.objects.get(character_id = uid)

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	return render(request, 'npc/npc-detail.html', context)

@login_required
def npc_create(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['edit_model'] = False
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.add_npc'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = NPCForm(data = request.POST)

		# check if valid
		if form.is_valid():
			# process the data
			article = form.save(commit = False)
			article.save()
			return HttpResponseRedirect('/npc/')

	else:
		context['form'] = NPCForm()

	return render(request, 'npc/npc-create.html', context)

@login_required
def npc_edit(request, uid):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['edit_model'] = True

	npc_instance = NPC.objects.get(character_id = uid)
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.change_npc'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = NPCForm(
			data = request.POST,
			instance = npc_instance)

		# check if valid
		if form.is_valid():
			# process the data
			article = form.save(commit = False)
			article.save()
			return HttpResponseRedirect('/npc/')

	else:
		context['form'] = NPCForm(instance = npc_instance)

	return render(request, 'npc/npc-create.html', context)

mystek/npc/templates/npc/npc-create.html
{% extends 'home/base.html' %}

{% block title %}Mystek - NPC - Create{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.form-header {
		font-size: 200%;
		padding: 0;
		color: red;
	}
	.form-body {
		width: 95%;
		height: auto;
		margin: 0 auto;
		text-align: center;
		background-color: #808080; /* gray */
	}
</style>
{% endblock %}

{% block local_script %}<script type="text/javascript"></script>{% endblock %}

{% block content %}
<br><br><br>
<div class="container-main">
	<p style="text-align: left; padding: 0; margin: 0;"><a href="{% url 'npc:npc_list' %}">&lt;back</a></p>
	<hr>
	<h1 class="form-header"><center>Project Wyrd: NPC</center></h1>
	<div class="story-how-to">
		<p><center>What data is needed? See the <a href="{% url 'npc:npc_help' %}">How-To</a> page for NPC's.</center></p>
	</div>
	<form class="form-body" method="post" enctype="multipart/form-data">
		{% if edit_model %}
		<h2 style="color: red;">EDIT</h2>
		{% endif %}
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
</div>
{% endblock %}

mystek/npc/templates/npc/npc-detail.html
{% extends 'home/base.html' %}

{% block title %}Mystek - {{ item.name }}{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main	{
		width: 100%;
		height: 100%;
	}
	.container-sub {
		width: 95%;
		height: auto;
		margin: 0 auto;
	}
	.story-title {
		width: 100%;
		height: 100px;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-title-left {
		width: 75%;
		height: auto;
		float: left;
		margin: 0;
		padding: 0;
		text-align: center;
	}
	.div-title-right {
		width: 19%;
		height: auto;
		float: left;
	}
	.div-content {
		width: 100%;
		height: auto;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-bin-master {
		width: 100%;
		height: 100px;
		margin: 0 auto;
		float: top;
		border: 1px solid black;
		background-color: #E6E6FA; /* lavender */
	}
	.div-bin-panel {
		width: 49%;
		height: auto;
		margin: 0 auto;
		float: left;
		text-align: left;
		background-color: #E6E6FA; /* lavender */
	}
	.pos-val {
		font-size: 120%;
		background-color: #90EE90; /* light green */
	}
	.neg-val {
		font-size: 120%;
		background-color: #FFB6C1; /* light pink */
	}
	.zro-val {
		font-size: 120%;
		background-color: #D3D3D3; /* light gray */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	<!-- sub container, which will only go to 95% width -->
	<br><br><br>
	<div class="options">
		<p style="padding: 0; margin: 0; float: left;"><a href="{% url 'npc:npc_list' %}">&lt;back</a></p>
		<p style="padding: 0; margin: 0; float: right;"><a href="{% url 'npc:npc_edit' uid=item.character_id %}">edit&gt;</a></p>
	</div>
	<br>
	<hr>
	<div class="container-sub">
		<!-- title goes here -->
		<div class="story-title">
			<div class="div-title-left">
				<h1>{{ item.name }}</h1>
				<p>{{ item.abst_world }}</p>
			</div>
			<div class="div-title-right">
				<h2><em>{{ item.character_id }}</em></h2>
			</div>
		</div>
		<div class="div-content">
			<br>
			<div class="div-bin-master">
				<div class="div-bin-panel">
					<p><strong>Reward Items:</strong></p>
				</div>
				<div class="div-bin-panel">
					{% for ri in item.reward_items.all %}
					<p><em>{{ ri.name }} - {{ ri.unique_id }}</em></p>
					{% empty %}
					<p><em>None</em></p>
					{% endfor %}
				</div>
			</div>
			<div class="div-bin-master">
				<div class="div-bin-panel">
					<p><strong>Reward Items Trigger:</strong></p>
				</div>
				<div class="div-bin-panel">
					{% if item.reward_items_trigger %}
					{{ item.reward_items_trigger }}
					{% else %}
					<p>N/A</p>
					{% endif %}
				</div>
			</div>
			<div class="div-bin-master" style="height: auto;">
				<h2><center>Character Dialog:</center></h2>
				<p>{{ item.character_dialog|linebreaks }}</p>
			</div>
			<hr>
			<p>{{ item.description|linebreaks }}</p>
		</div>
	</div>
</div>
{% endblock %}

mystek/npc/templates/npc/npc-help.html
{% extends 'home/base.html' %}

{% block title %}Mystek - NPC:Help{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
		margin: 0 auto;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.page-title-box {
		margin: 0 auto;
		width: auto;
		height: 95%;
		float: top;
	}
	.div-info-panel {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: top;
		background-color: #87CEFA;

	}
	.div-panel-title .div-panel-img .div-panel-info {
		margin: 0 auto;
		width: 90%;
		height: auto;
		float: top;
		background-color: #87CEFA;
	}
	.panel-image {
		max-width: 100%;
		max-height: 100%;
	}
	.panel-header {
		text-align: center;
	}
	.p-lalign {
		text-align: left;
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="container-main">
	<br><br>
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'npc:npc_create' %}">
					Create NPC
				</a>
			</li>
		</ul>
	</div>
	<div class="page-title-box">
		<h1 style="font-size: 300%;">NPC Help</h1>
	</div>
	<div class="div-info-panel" id="gen-name">
		<!-- for name -->
		<div class="div-panel-title">
			<h2 class="panel-header">Unique ID's</h2>
		</div>
		<div class="div-panel-info">
			<!-- basic info -->
			<p class="p-lalign">This (and other aspects) has been answered <a target="_blank" href="{% url 'achiev:achiev_help' %}#gen-uid">here&#x21D7;</a>. Check it out.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-itype">
		<div class="div-panel-title">
			<h2 class="panel-header">Item Type</h2>
		</div>
		<div class="div-panel-info">
			<p class="l-align">This (and other aspects) has been answered <a target="_blank" href="{% url 'armwep:armwep_help' %}#item-types-and-targets">here&#x21D7;</a>. Check it out.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel">
		<div class="div-panel-title">
			<h2 class="panel-header">Character Spawn World</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-npc-spawn-world.png" alt="Character Spawn World" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">The spawn world is the level which the NPC will spawn at. The code is written in LEVEL-FLOOR format; example: <strong>W0-1</strong>. The codes correspond to:</p>
			<ul>
				<li>Tutorial Level: <strong><code>W0</code></strong></li>
				<li>Castle Level: <strong><code>W1</code></strong></li>
				<li>Forrest Level: <strong><code>W2</code></strong></li>
				<li>Cavern Level: <strong><code>W3</code></strong></li>
				<li>Maze Level: <strong><code>W4</code></strong></li>
				<li>Library Level: <strong><code>W5</code></strong></li>
				<li>Abyss Level: <strong><code>W6</code></strong></li>
			</ul>
		</div>
	</div>
	<br>
	<div class="div-info-panel">
		<div class="div-panel-title">
			<h2 class="panel-header">Character Dialog</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-npc-chrdialog.png" alt="Character Dialog" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">Character Dialog is what the NPC will say to the player character's when interacted with. There lines should be separated by newlines (hitting enter on the keyboard), and dialog should exist between double-quotes (as in the image).</p>

			<p class="p-lalign">Responses to character dialog choices can also be written in: the options should be separated by 2 percent signs ( <strong>%%</strong> ) between the question and response, and 2 dollar signs ( <strong>$$</strong> ) between responses. Example:</p>

			<p class="p-lalign"><strong><em>"Do you have a potion? I need one."%%"Yes"::"Thanks"$$"No"::"Darn."</em></strong></p>

			<p class="p-lalign">Symbols explained:</p>

			<ul>
				<li><strong>%%</strong> Separates a question from the responses</li>
				<li><strong>$$</strong> Separates one response from another (ie: a "Yes" repsonse from a "No" response).</li>
				<li><strong>::</strong> This symbol <em>maps</em> a Player's repsonse (of say, "Yes") to an NPC's response to that response.</li>
			</ul>
		</div>
	</div>
	<br>
	<div class="div-info-panel">
		<div class="div-panel-title">
			<h2 class="panel-header">Reward Items &#47; Triggers</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-npc-ri.png" alt="Reward Items" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">Reward Items are items which the NPC will award to the player wehn a trigger is met. The Rewardable Items box does not allow for quantity specification, so if 3 of an item are to be awarded, indicate so in the description.</p>

			<p class="p-lalign">The Trigger is a flag  that will trigger the NPC giving the Rewardable Items to the player. The trigger is separated by a colon and consists of ITEM:CONDITION.</p>

			<p class="p-lalign">The items and conditions are as follows:</p>

			<h4>ITEM</h4>
			<p class="p-lalign">All items are given by their <a target="_blank" href="{% url 'achiev:achiev_help' %}#gen-uid">Unique ID&#x21D7;</a>. Acceptable UID's here are: Items, KeyItems and Party member codes; also World Codes are acceptable (given above).</p>

			<h4>CONDITION</h4>
			<p class="p-lalign">Coditions can be a quantity amounts (1-99, etc); also some predefined codes are acceptable. Examples:</p>

			<ul>
				<li><strong>W_END</strong> | indicates that a world is completely finished.</li>
				<li><strong>P_NUL</strong> | indicates that no party members were ever recruited.</li>
				<li><strong>PM_NUL</strong> | indicates that a given party member was never recruited.</li>
				<li>Etc.</li>
			</ul>
		</div>
	</div>
</div>
{% endblock %}

mystek/npc/templates/npc/npc-list.html
{% extends 'home/base.html' %}

{% block title %}Mystek - NPC List{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.obj-container {
		margin: 0 auto;
		width: 95%;
		height: 70px;
		float: top;
		background-color: #DCDCDC; /* gainsboro */
		border: 1px solid black;
	}
	.obj-sub-left {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: left;
		background-color: #DCDCDC; /* gainsboro */
	}
	.obj-sub-right {
		margin: 0 auto;
		width: 20%;
		height: auto;
		float: right;
		overflow: auto;
		overflow-y: auto;
		background-color: #DCDCDC; /* gainsboro */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	{% if logged_in %}
	<br><br>
	<!-- DEV_NOTE:02 -->
	<!-- top div, which will allow for navigating to the write-article form -->
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'npc:npc_create' %}">
					Create NPC
				</a>
			</li>
		</ul>
	</div>
	{% endif %}
	{% for npc in objects_list %}
	<br>
	<div class="obj-container">
		<!-- 80% -->
		<div class="obj-sub-left">
			<h4>
				<!-- goto mystek.com/dashboard/story/<slug>/ -->
				<a href="{% url 'npc:npc_detail' uid=npc.character_id %}">
					{{ npc.name }}
				</a>
			</h4>
			
		</div>
		<!-- 20% -->
		<div class="obj-sub-right">
			<h3><em>{{ npc.character_id }}</em></h3>
		</div>
	</div>
	<br>
	{% empty %}
	<br><br>
	<h1>Hey! There are no NPC's yet! :(</h1>
	<p>You can totally <a href="{% url 'npc:npc_create' %}">make</a> one, though. The more the merrier!</p>
	{% endfor %}
</div>
{% endblock %}