mystek/dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'

urlpatterns = [
	# https://mystek.com/dashboard/
    url(r'^$', views.index, name = 'index'),

    # STORY CLUSTER
    # https://mystek.com/dashboard/story/
    url(r'^story/$', views.story_list, name = 'story_list'),
    # https://mystek.com/dashboard/story/create/
    url(r'^story/create/$', views.story_create, name = 'story_create'),
    # https://mystek.com/dashboard/story/<slug>/
    url(r'^story/(?P<slug>[0-9a-zA-Z\-_]+)/$', views.story_detail, name = 'story_detail'),

    # OTHER CLUSTER
    # https://mystek.net/dashboard/todo/
    url(r'^todo/$', views.todo_create, name = 'todo_create'),
    # https://mystek.net/dashboard/change-passw/
    url(r'^change-passw/$', views.change_passw, name = 'change_passw'),

    # CUSTOM DENIAL URL
    url(r'^iperm/$', views.iperm, name = 'iperm'),
]

mystek/dashboard/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify

# Create your models here.
# two models here: todo and story


class Todo(models.Model):
	pub_date = models.DateTimeField(auto_now_add = True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
		blank = False,
		null = False,
		on_delete = models.CASCADE)
	content = models.TextField(
		max_length = 400,
		verbose_name = 'To Do Note')

	def __str__(self):
		return "To Do: %(d)s" % {
		'd': self.pub_date.strftime("%Y-%m-%d@%H:%M:%S")}


class Story(models.Model):
	title = models.CharField(
		max_length = 100,
		blank = False,
		default = '',
		verbose_name = 'Story Entry')
	slug = models.SlugField(max_length = 50, unique = True)
	chapter = models.CharField(
		max_length = 10,
		blank = False,
		default = '1',
		verbose_name = 'Story Chapter')
	content = models.TextField(
		max_length = 10000,
		blank = False,
		default = '',
		verbose_name = 'Content')
	pub_date = models.DateTimeField(auto_now_add = True)
	last_mod = models.DateTimeField(auto_now = True)

	def __str__(self):
		return "Story -- Chapter %(n)s" % {'n': self.chapter}

def create_slug(instance, new_slug = None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Story.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" % (slug, qs.first().id)
		return create_slug(instance, new_slug = new_slug)
	return slug

def pre_save_story(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_story, sender = Story)

mystek/dashboard/forms.py
from django.forms import ModelForm

from .models import Story, Todo


class StoryForm(ModelForm):
	class Meta:
		model = Story
		fields = [
			'title',
			'chapter',
			'content'
		]


class TodoForm(ModelForm):
	class Meta:
		model = Todo
		fields = [
			'content',
		]

mystek/dashboard/views.py
from django.conf import settings
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils import timezone

from .forms import StoryForm, TodoForm
from .models import Story, Todo

from site_news.models import Article

# Create your views here.
@login_required
def change_passw(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			_user = form.save()
			update_session_auth_hash(request, _user)
			return redirect('/')
	else:
		context['form'] = PasswordChangeForm(request.user)
	return render(request, 'dashboard/change-passw.html', context)

@login_required
def iperm(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpsResponseRedirect('/login/')

	return render(request, 'dashboard/denied.html', context)

@login_required
def story_create(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('dashboard.add_story'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = StoryForm(data = request.POST)

		# check if valid
		if form.is_valid():
			# process the data
			story = form.save(commit = False)
			story.pub_date = timezone.now()
			story.last_mod = timezone.now()
			story.save()
			return HttpResponseRedirect('/dashboard/story/')
	else:
		context['form'] = StoryForm() # if request == GET, send blank template

	return render(request, 'dashboard/story_create.html', context)

# template -- complete
# ugly, but it works
@login_required
def index(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	news_articles = Article.objects.filter(
		author = request.user).order_by('-pub_date')[0:5] # display (up to) 5 news articles

	if news_articles:
		context['news_articles'] = news_articles

	context['todos'] = Todo.objects.filter(
		user = request.user).order_by('-pub_date')[0:5] # display (up to) 5 todo notes


	# print("\n**********")
	# print(request.user.id)
	# print("**********\n")

	return render(request, 'dashboard/index.html', context)

# CLUSTER: story
@login_required
def story_list(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	item_list = Story.objects.all()
	paginator = Paginator(item_list, 30) # show 30 item listings at once

	page = request.GET.get('page')
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		# if page is not an integer, deliver first page
		items = paginator.page(1)
	except EmptyPage:
		# if page is out of range, deliver last page of results
		items = paginator.page(paginator.num_pages)

	context['entries'] = items

	return render(request, 'dashboard/story_list.html', context)

@login_required
def story_detail(request, slug):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	context['story'] = Story.objects.get(slug = slug)


	return render(request, 'dashboard/story_detail.html', context)

@login_required
def todo_create(request):
	context = dict()
	context['MEDIA_URL'] = settings.MEDIA_URL
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('dashboard.add_todo'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	#if POST
	if request.method == 'POST':
		form = TodoForm(data = request.POST)

		if form.is_valid():
			todo_note = form.save(commit = False)
			todo_note.user = request.user
			todo_note.pub_date = timezone.now()
			todo_note.save()
			return HttpResponseRedirect('/dashboard/')
	else:
		context['form'] = TodoForm()

	return render(request, 'dashboard/todo_create.html', context)

mystek/dashboard/templates/dashboard/change-passw.html
{% extends 'home/base.html' %}

{% block title %}Mystek - User - Change Password{% endblock %}

{% block local_style %}
<style type="text/css"></style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="container-main">
	<br><br><br>
	<h1 class="title">Change Password</h1>
	<form class="form-body" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Save Changes</button>
	</form>
</div>
{% endblock %}

mystek/dashboard/templates/dashboard/denied.html
{% extends 'home/base.html' %}

{% block title %}Insufficient Perms{% endblock %}

{% block local_style %}
<style type="text/css">
	.center-image {
		margin: 0 auto;
		width: auto;
		height: auto;
	}
	.div-image {
		max-width: 100%;
		max-height: 100%;
	}
</style>
{% endblock %}

{% block content %}
<div class="container-main">
	<br><br><br>
	<div class="center-image">
		<img class="div-image" src="{{ MEDIA_URL }}site-images/blackjack-gofish.png" alt="Lead Dev" />
	</div>
	<h1>Insufficient Permissions</h1>
	<p>Unfortunately, you do not have <strong><em>add/del/alt</em></strong> permissions for this app.</p>
</div>
{% endblock %}

mystek/dashboard/templates/dashboard/index.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Dashboard{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
		text-align: justify;
	}
	.article-nav {
		list-style-type: none;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
		border: 1px solid black;
	}
	.art-nav-item {
	    /* width;
	    added to try to make the dashboard nav look better; 2018-04-12 */
	    width: 9%;
		display: block;
		color: white;
		text-align: justify;
		padding: 14px 16px;
		text-decoration: none;
		float: left;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.container-inner {
		width: 95%;
		height: auto;
		margin: 0 auto;
		padding-bottom: 100px;
	}
	.user-news-articles {
		width: 55%;
		height: auto;
		margin: 0 auto;
		float: left;
		background-color: #F5F5F5; /* white smoke */
	}
	.user-to-do {
		width: 45%;
		height: auto;
		margin: 0 auto;
		float: right;
		background-color:  #FFE4E1; /* misty rose */
	}
	.div-user-na-brf {
		margin: 0 auto;
		width: 95%;
		height: auto;
		background-color: #E6E6FA; /* lavender */
	}
	.article-title {
		margin: 0 auto;
		width: 100%;
		height: auto;
		text-align: left;
		background-color: #E6E6FA; /* lavender */
	}
	.article-cont-tr {
		margin: 0 auto;
		width: 100%;
		height: auto;
		text-align: left;
		background-color: #E6E6FA; /* lavender */
	}
	.div-user-td {
		margin: 0 auto;
		width: 95%;
		height: auto;
		background-color: #FFB6C1; /* light pink */
	}
	.todo-pub-date {
		margin: 0 auto;
		width: 100%
		height: auto;
		background-color: #FFB6C1; /* light pink */
	}
	.todo-content {
		margin: 0 auto;
		width: 100%;
		height: auto;
		background-color: #FFB6C1; /* light pink */
	}
	.todo-top-panel {
		margin: 0 auto;
		width: 100%;
		height: auto;
		text-align: center;
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# https://mystek.com/dashboard/

DEV_NOTES:
preferred datetime display: Y-m-d@H:i:s # Year-month-day@Hour:minute:second

# DJANGO_NOTE
01: this will be a small list of news articles which the user has created
	max: 5 articles
02: this will be a small list of to-do notes, which can be written by a
	user to detail where they left off and what they need to do.
03:	NEEDED FUNCTIONALITY -- when in mystek.com/news/<slug>/, there needs to be an
	option for logged users to edit the news article
#}

{% block content %}
<div class="container-main">
	<br><br>
	{% if logged_in %}
	<!-- DEV_NOTE:02 -->
	<!-- top div, which will allow for navigating to the write-article form -->
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'dashboard:change_passw' %}">Change Password</a>
			</li>
		</ul>
		
		<!-- line items: left -> list view; right -> add new entry -->
		<ul class="article-nav">
			<li class="art-nav-item">
				<a href="{% url 'item:item_list' %}">Items&#58;</a>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'item:item_create' %}">Add</a>
			</li>
			<li class="art-nav-item">
				<span></span>
				<span>|</span>
				<span></span>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'keyitem:keyitem_list' %}">KeyItems&#58;</a>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'keyitem:keyitem_create' %}">Add</a>
			</li>
			<li class="art-nav-item">
				<span></span>
				<span>|</span>
				<span></span>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'armwep:armwep_list' %}">Armor &#47; Weapons&#58;</a>
				<li class="art-nav-item">
				<a href="{% url 'armwep:armwep_create' %}">Add</a>
			</li>
			</li>
		</ul>

		<!-- user console line 2 -->
		<ul class="article-nav">
			<li class="art-nav-item">
				<a href="{% url 'stateff:stateff_list' %}">Status Effect&#58;</a>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'stateff:stateff_create' %}">Add</a>
			</li>
			<li class="art-nav-item">
				<span></span>
				<span>|</span>
				<span></span>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'npc:npc_list' %}">NPC&#58;</a>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'npc:npc_create' %}">Add</a>
			</li>
			<li class="art-nav-item">
				<span></span>
				<span>|</span>
				<span></span>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'achiev:achiev_list' %}">Achievements&#58;</a>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'achiev:achiev_create' %}">Add</a>
			</li>
		</ul>

		<!-- user console line 3 -->
		<ul class="article-nav">
			<li class="art-nav-item">
				<a href="{% url 'dashboard:story_list' %}">Story&#58;</a>
			</li>
			<li class="art-nav-item">
				<a href="{% url 'dashboard:story_create' %}">
					Write a Page
				</a>
			</li>
			
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'site_news:create_article' %}">Write an Article</a>
			</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'site_news:index' %}">News Article&#58;</a>
			</li>
			
		</ul>
	</div>
	{% endif %}
	<br>
	<div class="container-inner">
		<!-- articles written by user -->
		<div class="user-news-articles">
			<!-- see DJANGO_NOTE:01 -->
			{% for article in news_articles %}
			<div class="div-user-na-brf">
				<div class="article-title">
					<!-- link to the article, for some quick review; also see DJANGO_NOTE:03 -->
					<a href="{% url 'site_news:article_detail' slug=article.slug %}">{{ article.title|truncatechars:80 }}</a> &raquo; {{ article.pub_date|date:'Y-m-d@H:i:s' }}
				</div>
				<div class="article-cont-tr">
					{{ article.content|truncatechars:200 }}
				</div>
			</div>
			<br>
			{% empty %}
			<h3>You haven't authored a news article yet.</h3>
			{% endfor %}
		</div>

		<!-- todo notes written by user -->
		<div class="user-to-do">
			<!-- see DJANGO_NOTE:02 -->
			<div class="todo-top-panel">
				To-Do Notes ----- <a href="{% url 'dashboard:todo_create' %}">+</a>
			</div>
			{% for todo in todos %}
			<div class="div-user-td">
				<div class="todo-pub-date">
					To Do: {{ todo.pub_date|date:'Y-m-d@H:i:s' }}
				</div>
				<div class="todo-content">
					{{ todo.content|linebreaks }}
				</div>
			</div>
			<br>
			{% empty %}
			<h5>No notes written, <a href="{% url 'dashboard:todo_create' %}">write</a> one?</h5>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

mystek/dashboard/templates/dashboard/story_create.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Story - Create{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.form-header {
		font-size: 200%;
		padding: 0;
		color: red;
	}
	.form-body {
		width: 95%;
		height: auto;
		margin: 0 auto;
		text-align: center;
		background-color: #808080; /* gray */
	}
</style>
{% endblock %}

{% block local_script %}<script type="text/javascript"></script>{% endblock %}

{% block content %}
<br><br><br>
<div class="container-main">
	<p style="text-align: left; padding: 0; margin: 0;"><a href="{% url 'dashboard:story_list' %}">&lt;back</a></p>
	<hr>
	<h1 class="form-header"><center>Project Wyrd: Story Chapter</center></h1>
	<div class="story-how-to">
		<p><center>What data is needed? See the <a href="#">How-To</a> page for Stories.</center></p>
	</div>
	<form class="form-body" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
</div>
{% endblock %}

mystek/dashboard/templates/dashboard/story_detail.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Story List{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main	{
		width: 100%;
		height: 100%;
	}
	.container-sub {
		width: 95%;
		height: auto;
		margin: 0 auto;
	}
	.story-title {
		width: 100%;
		height: 100px;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-title-left {
		width: 75%;
		height: auto;
		float: left;
		margin: 0;
		padding: 0;
		text-align: center;
	}
	.div-title-right {
		width: 19%;
		height: auto;
		float: left;
	}
	.div-content {
		width: 100%;
		height: auto;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-bt-meta {
		width: 100%;
		height: auto;
		margin: 0 auto;
		float: top;
		background-color: #EEA0FA; /* lavender */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	<!-- sub container, which will only go to 95% width -->
	<br><br><br>
	<p style="padding: 0; margin: 0;"><a href="{% url 'dashboard:story_list' %}">&lt;back</a></p>
	<hr>
	<div class="container-sub">
		<!-- title goes here -->
		<div class="story-title">
			<div class="div-title-left">
				<h1>{{ story.title }}</h1>
			</div>
			<div class="div-title-right">
				<p><strong>Chapter {{ story.chapter }}</strong></p>
				<p><strong>Published:</strong> <em>{{ story.pub_date|date:'Y-m-d@H:i:s' }}</em></p>
			</div>
		</div>
		<div class="div-content">
			<p>{{ story.content|linebreaks }}</p>
		</div>
		<div class="div-bt-meta">
			<p><strong>Last Modifed:</strong> <em>{{ story.last_mod|date:'Y-m-d@H:i:s' }}</em></p>
		</div>
	</div>
</div>
{% endblock %}

mystek/dashboard/templates/dashboard/story_list.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Story List{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.obj-container {
		margin: 0 auto;
		width: 95%;
		height: 100px;
		float: top;
		background-color: #DCDCDC; /* gainsboro */
		border: 1px solid black;
	}
	.obj-sub-left {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: left;
		background-color: #DCDCDC; /* gainsboro */
	}
	.obj-sub-right {
		margin: 0 auto;
		width: 20%;
		height: auto;
		float: right;
		overflow: auto;
		overflow-y: auto;
		background-color: #DCDCDC; /* gainsboro */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	{% if logged_in %}
	<br><br>
	<!-- DEV_NOTE:02 -->
	<!-- top div, which will allow for navigating to the write-article form -->
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right"><a href="{% url 'dashboard:story_create' %}">Write an Entry</a></li>
		</ul>
	</div>
	{% endif %}
	{% for entry in entries %}
	<br>
	<div class="obj-container">
		<!-- 80% -->
		<div class="obj-sub-left">
			<h4>
				<!-- goto mystek.com/dashboard/story/<slug>/ -->
				<a href="{% url 'dashboard:story_detail' slug=entry.slug %}">
					{{ entry.title }}
				</a>
			</h4>
			<p style="padding: 0; margin: 0;">{{ entry.pub_date|date:'Y-m-d@H:i:s' }}</p>
		</div>
		<!-- 20% -->
		<div class="obj-sub-right">
			<h3><em>Chapter: {{ entry.chapter }}</em></h3>
		</div>
	</div>
	<br>
	{% empty %}
	<br><br>
	<h1>Hey! There's no entries yet! :(</h1>
	<p>You can totally <a href="{% url 'dashboard:story_create' %}">write</a> one, though. If ya got the skills.</p>
	{% endfor %}
</div>
{% endblock %}

mystek/dashboard/templates/dashboard/todo_create.html
{% extends 'home/base.html' %}

{% block title %}Mystek - To-Do Note - Create{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.container-child {
		margin: 0 auto;
		width: 80%;
		height: auto;
	}
	.div-panel-title {
		width: 100%;
		height: auto;
	}
	.div-panel-content {
		width: 100%;
		height: auto;
	}
	.form-body {
		width: 95%;
		height: auto;
		margin: 0 auto;
		text-align: center;
		background-color: #808080; /* gray */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="container-main">
	<br><br><br>
	<div class="container-child">
		<div class="div-panel-title">
			<h1 class="panel-title">To-Do Note</h1>
		</div>
		<div class="div-panel-content">
			<form class="form-body" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit">Submit</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}