mystek/armwep/urls.py
from django.conf.urls import url

from . import views

app_name = 'armwep'

urlpatterns = [
	# ARMOR & WEAPON CLUSTER
    # https://mystek.com/dashboard/armwep/
    url(r'^$', views.armwep_list, name = 'armwep_list'),
    # https://mystek.com/dashboard/armwep/<uid>
    url(r'^(?P<uid>0x[0-9A-F]+)/$', views.armwep_detail, name = 'armwep_detail'),
    # https://mystek.com/dashboard/armwep/create
    url(r'^create/$', views.armwep_create, name = 'armwep_create'),
    url(r'^edit/(?P<uid>0x[0-9A-F]+)/$', views.armwep_edit, name = 'armwep_edit'),
    url(r'^help/$', views.armwep_help, name = 'armwep_help'),
]

mystek/armwep/models.py
from django.db import models

# Create your models here.

mystek/armwep/forms.py
from django.forms import ModelForm

from registry.models import ArmorWeapon


class ArmWepForm(ModelForm):
	class Meta:
		model = ArmorWeapon
		fields = [
			'name',
			'unique_id',
			'in_game_description',
			'description',
			'item_type',
			'item_type2',
			'target',
			'target2',
			'drop_weight',
			'effect_value',
			'status_effect',
			'buy_price',
			'sell_price',
		]

mystek/armwep/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import ArmWepForm

from registry.models import ArmorWeapon

# Create your views here.
########################
# CLUSTER 2: ArmorWeapon
########################
@login_required
def armwep_list(request):	# finisihed 1/2
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	item_list = ArmorWeapon.objects.all()
	paginator = Paginator(item_list, 30) # show 30 item listings at once

	page = request.GET.get('page')
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		# if page is not an integer, deliver first page
		items = paginator.page(1)
	except EmptyPage:
		# if page is out of range, deliver last page of results
		items = paginator.page(paginator.num_pages)

	context['armweps'] = items

	return render(request, 'armwep/armwep-list.html', context)

@login_required
def armwep_help(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.add_armorweapon'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	return render(request, 'armwep/armwep-help.html', context)

@login_required
def armwep_detail(request, uid):	# finisihed 1/2
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['aw'] = ArmorWeapon.objects.get(unique_id = uid)

	if context['aw'].effect_value > 0:
		context['polar_val'] = 'pos-val'
		context['pol_sym'] = "+"
	elif context['aw'].effect_value < 0:
		context['polar_val'] = 'neg-val'
		context['pol_sym'] = "-"
	else:
		context['polar_val'] = 'zro-val'
		context['pol_sym'] = "&plusmn;"

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	return render(request, 'armwep/armwep-detail.html', context)

@login_required
def armwep_create(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['edit_model'] = False
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.add_armorweapon'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = ArmWepForm(data = request.POST)

		# check if valid
		if form.is_valid():
			# process the data
			article = form.save(commit = False)
			article.is_active = False
			article.save()
			return HttpResponseRedirect('/armwep/')

	else:
		context['form'] = ArmWepForm()

	return render(request, 'armwep/armwep-create.html', context)

@login_required
def armwep_edit(request, uid):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['edit_model'] = True

	armwep_instance = ArmorWeapon.objects.get(unique_id = uid)
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.change_armorweapon'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = ArmWepForm(
			data = request.POST,
			instance = armwep_instance)

		# check if valid
		if form.is_valid():
			# process the data
			article = form.save(commit = False)
			article.is_active = False
			article.save()
			return HttpResponseRedirect('/armwep/')

	else:
		context['form'] = ArmWepForm(instance = armwep_instance)

	return render(request, 'armwep/armwep-create.html', context)

mystek/armwep/templates/armwep/armwep-create.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Armor &#47; Weapon - Create{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.form-header {
		font-size: 200%;
		padding: 0;
		color: red;
	}
	.form-body {
		width: 95%;
		height: auto;
		margin: 0 auto;
		text-align: center;
		background-color: #808080; /* gray */
	}
</style>
{% endblock %}

{% block local_script %}<script type="text/javascript"></script>{% endblock %}

{% block content %}
<br><br><br>
<div class="container-main">
	<p style="text-align: left; padding: 0; margin: 0;"><a href="{% url 'armwep:armwep_list' %}">&lt;back</a></p>
	<hr>
	<h1 class="form-header"><center>Project Wyrd: Armor &#47; Weapon</center></h1>
	<div class="story-how-to">
		<p><center>What data is needed? See the <a href="{% url 'armwep:armwep_help' %}">How-To</a> page for Armor &#47; Weapons.</center></p>
	</div>
	<form class="form-body" method="post" enctype="multipart/form-data">
		{% if edit_model %}
		<h2 style="color: red;"">EDIT</h2>
		{% endif %}
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
</div>
{% endblock %}

mystek/armwep/templates/armwep/armwep-detail.html
{% extends 'home/base.html' %}

{% block title %}Mystek - {{ aw.name }}{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main	{
		width: 100%;
		height: 100%;
	}
	.container-sub {
		width: 95%;
		height: auto;
		margin: 0 auto;
	}
	.story-title {
		width: 100%;
		height: 100px;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-title-left {
		width: 75%;
		height: auto;
		float: left;
		margin: 0;
		padding: 0;
		text-align: center;
	}
	.div-title-right {
		width: 19%;
		height: auto;
		float: left;
	}
	.div-content {
		width: 100%;
		height: auto;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-bin-master {
		width: 100%;
		height: 100px;
		margin: 0 auto;
		float: top;
		border: 1px solid black;
		background-color: #E6E6FA; /* lavender */
	}
	.div-bin-panel {
		width: 49%;
		height: auto;
		margin: 0 auto;
		float: left;
		text-align: left;
		background-color: #E6E6FA; /* lavender */
	}
	.pos-val {
		font-size: 120%;
		background-color: #90EE90; /* light green */
	}
	.neg-val {
		font-size: 120%;
		background-color: #FFB6C1; /* light pink */
	}
	.zro-val {
		font-size: 120%;
		background-color: #D3D3D3; /* light gray */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	<!-- sub container, which will only go to 95% width -->
	<br><br><br>
	<div class="options">
		<p style="padding: 0; margin: 0; float: left;"><a href="{% url 'armwep:armwep_list' %}">&lt;back</a></p>
		<p style="padding: 0; margin: 0; float: right;"><a href="{% url 'armwep:armwep_edit' uid=aw.unique_id %}">edit&gt;</a></p>
	</div>
	<br>
	<hr>
	<div class="container-sub">
		<!-- title goes here -->
		<div class="story-title">
			<div class="div-title-left">
				<h1>{{ aw.name }}</h1>
			</div>
			<div class="div-title-right">
				<h2><em>{{ aw.unique_id }}</em></h2>
			</div>
		</div>
		<div class="div-content">
			<q><strong><em>{{ aw.in_game_description|linebreaks }}</em></strong></q>
			<br>
			<div class="div-bin-master">
				<div class="div-bin-panel">
					<p><strong>Item Type: <em>{{ aw.item_type }}.{{ aw.item_type2 }}</em></strong></p>
				</div>
				<div class="div-bin-panel">
					<p><strong>Target: <em>{{ aw.target }}.{{ aw.target2 }}</em></strong></p>
				</div>
			</div>
			<div class="div-bin-master">
				<div class="div-bin-panel">
					<p><strong>Item Drop Weight: <em>{{ aw.drop_weight }}&#47;1000</em></strong></p>
				</div>
				<div class="div-bin-panel">
					<p><strong>Buy Price: <em>{{ aw.buy_price }}</em></strong></p>
					<p><strong>Sell Price: <em>{{ aw.sell_price }}</em></strong></p>
				</div>
			</div>
			<div class="div-bin-master">
				<div class="div-bin-panel">
					<p><strong>Effect Value:</strong></p>
				</div>
				<div class="div-bin-panel {{ polar_var }}">
					<p>{{ aw.target }}.{{ aw.target2 }} {{ pol_sym }}{{ aw.effect_value }}</p>
				</div>
			</div>
			<div class="div-bin-master">
				{% if aw.status_effect %}
				<p><strong>Status Effect: <em>{{ aw.status_effect.name }}</em></strong>; Effect Type: {{ aw.status_effect.abst_type }}</p>
				}
				{% else %}
				<p><strong>Status Effect:</strong> <code>None</code>.</p>
				{% endif %}
			</div>
			<hr>
			<p>{{ aw.description|linebreaks }}</p>
		</div>
	</div>
</div>
{% endblock %}

mystek/armwep/templates/armwep/armwep-help.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Armor &#47; Weapons:Help{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
		margin: 0 auto;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.page-title-box {
		margin: 0 auto;
		width: auto;
		height: 95%;
		float: top;
	}
	.div-info-panel {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: top;
		background-color: #87CEFA;

	}
	.div-panel-title .div-panel-img .div-panel-info {
		margin: 0 auto;
		width: 90%;
		height: auto;
		float: top;
		background-color: #87CEFA;
	}
	.panel-image {
		max-width: 100%;
		max-height: 100%;
	}
	.panel-header {
		text-align: center;
	}
	.p-lalign {
		text-align: left;
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="container-main">
	<br><br>
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'armwep:armwep_create' %}">
					Create Armor &#47; Weapons
				</a>
			</li>
		</ul>
	</div>
	<div class="page-title-box">
		<h1 style="font-size: 300%;">Armor &#47; Weapons Help</h1>
	</div>
	<div class="div-info-panel" id="gen-name">
		<!-- for name -->
		<div class="div-panel-title">
			<h2 class="panel-header">Unique ID's</h2>
		</div>
		<div class="div-panel-info">
			<!-- basic info -->
			<p class="p-lalign">This (and other aspects) has been answered <a target="_blank" href="{% url 'achiev:achiev_help' %}#gen-uid">here&#x21D7;</a>. Check it out.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="item-types-and-targets">
		<div class="div-panel-title">
			<h2 class="panel-header">Item Type and Target</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-armwep-type12.png" alt="Item Type(s)" /></center>
		</div>
		<div class="div-panel-info">
			<h3>Item Types:</h3>
			<p class="p-lalign">Item types describe what the item is. Armor, weapons &#47; items all have this field. The item types correspond to the inventory categories in-game. There are several categories for each. They are:</p>
			<h4>Item Type 1</h4>
			<ul>
				<li><code>health</code> &#9; <em># all healing items</em></li>
				<li><code>weapon</code> &#9;<em># this category has sub-categories</em></li>
				<li><code>misc</code> &#9; <em># all items which are not health-related, such as ingredients, etc.</em></li>
				<li><code>armor</code> &#9; <em># this category has sub-categories</em></li>
				<li><code>keyitem</code> &#9; <em># all keyitems</em></li>
			</ul>
			<br>
			<h3>Item Type 2, if Weapon</h3>
			<ul>
				<li><code>sword</code> &#9; <em># sub-weapon; all swords</em></li>
				<li><code>hammer</code> &#9; <em>#sub-weapon; all hammer-like weapons</em></li>
				<li><code>bow-arrow</code> &#9; <em># sub-weapon; all bow-arrow weapons</em></li>
			</ul>
			<br>
			<h3>Item Type 2, if Armor</h3>
			<ul>
				<li><code>helm</code> &#9; <em># sub-armor; all helm-type armor</em></li>
				<li><code>body</code> &#9; <em>#sub-armor; all mid-body armor</em></li>
				<li><code>shield</code> &#9; <em>#sub-armor; all shields</em></li>
			</ul>
			<hr>
			<br>
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-items-itarg.png" alt="gen-itarg" /></center>
			<br>
			<h3>Item Targets:</h3>
			<p class="p-lalign">The Item Target(s) are the apsect of the Character which the item will affect. The <code>itype1</code> handles the "broad" target, while <code>itype2</code> handles the "spec" target. The categories are:</p>
			<h4>Item Target[1] (the "broad" target)</h4>
			<ul>
				<li><code>player</code> &#9; <em># broad target: the player character</em></li>
				<li><code>enemy</code> &#9; <em># broad target: the enemy character</em></li>
				<li><code>party</code> &#9; <em># broad target: any character in the player's party</em></li>
				<li><code>overworld</code> &#9; <em># broad target: affect the overworld, the "spec" targets are different from items which target Character objects</em></li>
			</ul>
			<br>
			<h4>Item Target[2] (the "spec" target)</h4>
			<ul>
				<li><code>hp</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects health points</em></li>
				<li><code>sp</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects stamina points</em></li>
				<li><code>ma</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects magic points</em></li>
				<li><code>thp</code> | applicable broad targets: [player, party] &#9; <em># item affects total health points</em></li>
				<li><code>tsp</code> | applicable broad targets: [player, party] &#9; <em># item affects total stamina points</em></li>
				<li><code>tma</code> | applicable broad targets: [player, party] &#9; <em># item affects total magic points</em></li>
				<li><code>atk</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects attack strength</em></li>
				<li><code>def</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects defense strength</em></li>
				<li><code>agl</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects agility</em></li>
				<li><code>dex</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects dexterity</em></li>
				<li><code>int</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects intelligence</em></li>
				<li><code>wil</code> | applicable broad targets: [player, enemy, party] &#9; <em># item affects will</em></li>
				<li><code>lvl</code> | applicable broad targets: [player, party] &#9; <em># item affects character Level</em></li>
				<li><code>sfx</code> | applicable broad targets: [player, party] &#9; <em># item affects status effects, all</em></li>
				<li><code>stat:&lt;status_effect:unique_id&gt;</code> | applicable broad targets: [player, party] &#9; <em>item affects specific status effect; example: <code>stat:0xB001</code></em></li>
				<li><code>enemy_F</code> | applicable broad targets: [overworld] &#9; <em># item affects the final boss of a level</em></li>
			</ul>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-dw">
		<div class="div-panel-title">
			<h2 class="panel-header">Drop Weight</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-armwep-dw1000.png" alt="Drop Weight" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">The drop weight of the item. Requires a value of 0-1000; the higher the value, the more likely an item is to drop for the player; the lower the value, the rarer the item.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-sv">
		<div class="div-panel-title">
			<h2 class="panel-header">Stat Value</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-armwep-sv.png" alt="Stat Value" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">The Stat Value is the number value which affects the "spec" target. Example, a value of 20 where targets are: player.hp, then the item will increase (current) HP by 20.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-stateff">
		<div class="div-panel-title">
			<h2 class="panel-header">Status Effects</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-armwep-seff.png" alt="Status Effect" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">Potential effects to attach to the item(s). Only 1 status effect can be attached per item.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-bpsp">
		<div class="div-panel-title">
			<h2 class="panel-header">Buying Price / Selling Price</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-armwep-bpsp.png" alt="gen BPSP" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">The buying price for the item and the selling price for the item. If the item isn't meant to be sold, set the price as <code>-1</code>.</p>
		</div>
	</div>
	<br>
</div>
{% endblock %}

mystek/armwep/templates/armwep/armwep-list.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Armor &#47; Weapons List{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.obj-container {
		margin: 0 auto;
		width: 95%;
		height: 70px;
		float: top;
		background-color: #DCDCDC; /* gainsboro */
		border: 1px solid black;
	}
	.obj-sub-left {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: left;
		background-color: #DCDCDC; /* gainsboro */
	}
	.obj-sub-right {
		margin: 0 auto;
		width: 20%;
		height: auto;
		float: right;
		overflow: auto;
		overflow-y: auto;
		background-color: #DCDCDC; /* gainsboro */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	{% if logged_in %}
	<br><br>
	<!-- DEV_NOTE:02 -->
	<!-- top div, which will allow for navigating to the write-article form -->
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'armwep:armwep_create' %}">
					Create Armor&#47;Weapon
				</a>
			</li>
		</ul>
	</div>
	{% endif %}
	{% for aw in armweps %}
	<br>
	<div class="obj-container">
		<!-- 80% -->
		<div class="obj-sub-left">
			<h4>
				<!-- goto mystek.com/dashboard/story/<slug>/ -->
				<a href="{% url 'armwep:armwep_detail' uid=aw.unique_id %}">
					{{ aw.name }}
				</a>
			</h4>
			
		</div>
		<!-- 20% -->
		<div class="obj-sub-right">
			<h3><em>{{ aw.unique_id }}</em></h3>
		</div>
	</div>
	<br>
	{% empty %}
	<br><br>
	<h1>Hey! There are no Armor &#47; Weapons yet! :(</h1>
	<p>You can totally <a href="{% url 'armwep:armwep_create' %}">make</a> one, though. It's dangerous to go alone!</p>
	{% endfor %}
</div>
{% endblock %}