mystek/achiev/urls.py
from django.conf.urls import url

from . import views

app_name = 'achiev'

urlpatterns = [
	# ACHIEV CLUSTER
    # https://mystek.com/dashboard/achiev/
    url(r'^$', views.achiev_list, name = 'achiev_list'),
    # https://mystek.com/dashboard/achiev/<uid>/
    url(r'^(?P<uid>X[0-9]+)/$', views.achiev_detail, name = 'achiev_detail'),
    # https://mystek.com/dashboard/achiev/create/
    url(r'^create/$', views.achiev_create, name = 'achiev_create'),
    # https://mystek.com/achiev/edit
    url(r'^edit/(?P<uid>X[0-9]+)/$', views.achiev_edit, name = 'achiev_edit'),
    url(r'^help/$', views.achiev_help, name = 'achiev_help'),
]

mystek/achiev/models.py
from django.db import models

# Create your models here.

mystek/achiev/forms.py
from django.forms import ModelForm

from registry.models import Achievement


class AchievementForm(ModelForm):
	class Meta:
		model = Achievement
		fields = [
			'name',
			'unique_id',
			'in_game_description',
			'description',
		]

mystek/achiev/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import AchievementForm

from registry.models import Achievement

# Create your views here.
########################
# CLUSTER 1: Achievement
########################
@login_required
def achiev_list(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	item_list = Achievement.objects.all()
	paginator = Paginator(item_list, 30) # show 30 item listings at once

	page = request.GET.get('page')
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		# if page is not an integer, deliver first page
		items = paginator.page(1)
	except EmptyPage:
		# if page is out of range, deliver last page of results
		items = paginator.page(paginator.num_pages)

	context['objects_list'] = items

	return render(request, 'achiev/index.html', context)

@login_required
def achiev_help(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
		if context['user'].has_perm('registry.add_achievement'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	return render(request, 'achiev/achiev-help.html', context)

@login_required
def achiev_detail(request, uid):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['achiev'] = Achievement.objects.get(unique_id = uid)

	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user
	else:
		return HttpResponseRedirect('/login/')

	return render(request, 'achiev/achiev_detail.html', context)

@login_required
def achiev_create(request):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['edit_model'] = False
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.add_achievement'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = AchievementForm(data = request.POST)

		# check if valid
		if form.is_valid():
			# process the data
			article = form.save(commit = False)
			article.save()
			return HttpResponseRedirect('/achiev/')

	else:
		context['form'] = AchievementForm()

	return render(request, 'achiev/achiev_create.html', context)

@login_required
def achiev_edit(request, uid):
	context = dict()

	context['MEDIA_URL'] = settings.MEDIA_URL
	context['edit_model'] = True

	achiev_instance = Achievement.objects.get(unique_id = uid)
	
	if request.user.is_authenticated:
		context['logged_in'] = True
		context['user'] = request.user

		if context['user'].has_perm('registry.change_achievement'):
			pass
		else:
			return HttpResponseRedirect('/dashboard/iperm/')
	else:
		return HttpResponseRedirect('/login/')

	# if POST
	if request.method == 'POST':
		form = AchievementForm(
			data = request.POST,
			instance = achiev_instance)

		# check if valid
		if form.is_valid():
			# process the data
			article = form.save(commit = False)
			article.is_active = False
			article.save()
			return HttpResponseRedirect('/achiev/')

	else:
		context['form'] = AchievementForm(instance = achiev_instance)

	return render(request, 'achiev/achiev_create.html', context)

mystek/achiev/templates/achiev/achiev-help.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Achievements:Help{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
		margin: 0 auto;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.page-title-box {
		margin: 0 auto;
		width: auto;
		height: 95%;
		float: top;
	}
	.div-info-panel {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: top;
		background-color: #87CEFA;

	}
	.div-panel-title .div-panel-img .div-panel-info {
		margin: 0 auto;
		width: 90%;
		height: auto;
		float: top;
		background-color: #87CEFA;
	}
	.panel-image {
		max-width: 100%;
		max-height: 100%;
	}
	.panel-header {
		text-align: center;
	}
	.p-lalign {
		text-align: left;
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="container-main">
	<br><br>
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'achiev:achiev_create' %}">
					Create Achievement
				</a>
			</li>
		</ul>
	</div>
	<div class="page-title-box">
		<h1 style="font-size: 300%;">Achievements Help</h1>
	</div>
	<div class="div-info-panel" id="gen-name">
		<!-- for name -->
		<div class="div-panel-title">
			<h2 class="panel-header">Achievement: Name</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-achiev-name.png" alt="Achievement name" /></center>
		</div>
		<div class="div-panel-info">
			<!-- basic info -->
			<p class="p-lalign">The Achievement name is the displayed name in the game. Max Length is 100 characters.</p>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-uid">
		<div class="div-panel-title">
			<h2 class="panel-header">Achievement: Unique ID</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-achiev-uid.png" alt="generic Unique ID" /></center>
		</div>
		<div class="div-panel-info">
			<p class="p-lalign">The Unique ID is the primary identifier for <strong>all</strong> objects in the game. The Achievements are the <em>ONLY</em> items to have a different UID scheme compared to the other items.</p>
			<h3 class="p-lalign">Achievement UID's</h3>
			<p class="p-lalign">All Achievement UID's start with a capital <code>X</code>. It is 4 characters long (eg. <code>X001</code>), and is a simply an incrementing value, giving a total possible number of Achievements: 999. Max length is 4 characters. Examples:</p>
			<ul>
				<li><code>X001</code>, <code>X002</code>, ..., <code>X009</code></li>
				<li><code>X010</code>, <code>X011</code>, ..., <code>X099</code></li>
				<li><code>X100</code>, <code>X101</code>, ..., <code>X199</code></li>
			</ul>
			<h3 class="p-lalign">Other UID's</h3>
			<p>Other objects use Hexideicimal codes as their UID's. They must start with <code>0x</code>, and their next character correspons to their appropriate item type. Max length is 6 characters. Those item types are:</p>
			<ul>
				<li>Armor &#47; Weapons: 0xA--- # 4095 total possible items</li>
				<li>Item: 0x10-- # 255 total possible items</li>
				<li>KeyItem: 0x11-- # 255 total possible items</li>
				<li>NPC: 0xC--- # 4095 total possible items</li>
				<li>Status Effect: 0xB--- #4095 possible items</li>
			</ul>
			<p>Hexcodes go from: 0-F.</p>
			<ul>
				<li>0 - 9: 0-9 # same as decimal numbers</li>
				<li>10 - 15: A-F # 10 = A, 11 = B, and so on</li>
				<li>16 - 31: 10-1F # and so on and so forth</li>
			</ul>
		</div>
	</div>
	<br>
	<div class="div-info-panel" id="gen-igdesc">
		<div class="div-panel-title">
			<h2>In-Game Description</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-achiev-igd.png" alt="generic igdesc" /></center>
		</div>
		<div class="div-panel-info">
			<p>The In-Game Description is the text that will appear in-game to describe the item. Max length is 200 characters.</p>
		</div>
	</div>
	<div class="div-info-panel" id="gen-desc">
		<div class="div-panel-title">
			<h2>Description</h2>
		</div>
		<div class="div-panel-img">
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-achiev-desc.png" alt="Achievement description" /></center>
			<br>
			<center><img class="panel-image" src="{{ MEDIA_URL }}site-images/help/mystek-desc.png" alt="generic description" /></center>
		</div>
		<div class="div-panel-info">Author's/Programmer's description of item, including explanations, stats, etc. Max length is 300 characters. This description is for the benefit of the programmers, will not show up in-game.</div>
	</div>
</div>
{% endblock %}

mystek/achiev/templates/achiev/achiev_create.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Achievement - Create{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.form-header {
		font-size: 200%;
		padding: 0;
		color: red;
	}
	.form-body {
		width: 95%;
		height: auto;
		margin: 0 auto;
		text-align: center;
		background-color: #808080; /* gray */
	}
</style>
{% endblock %}

{% block local_script %}<script type="text/javascript"></script>{% endblock %}

{% block content %}
<br><br><br>
<div class="container-main">
	<p style="text-align: left; padding: 0; margin: 0;"><a href="{% url 'achiev:achiev_list' %}">&lt;back</a></p>
	<hr>
	<h1 class="form-header"><center>Project Wyrd: Achievement</center></h1>
	<div class="story-how-to">
		<p><center>What data is needed? See the <a href="{% url 'achiev:achiev_help' %}">How-To</a> page for Achievements.</center></p>
	</div>
	<form class="form-body" method="post" enctype="multipart/form-data">
		{% if edit_model %}
		<h2 style="color: red;">EDIT</h2>
		{% endif %}
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
	</form>
</div>
{% endblock %}

mystek/achiev/templates/achiev/achiev_detail.html
{% extends 'home/base.html' %}

{% block title %}Mystek - {{ achiev.name }}{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main	{
		width: 100%;
		height: 100%;
	}
	.container-sub {
		width: 95%;
		height: auto;
		margin: 0 auto;
	}
	.story-title {
		width: 100%;
		height: 100px;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
	.div-title-left {
		width: 75%;
		height: auto;
		float: left;
		margin: 0;
		padding: 0;
		text-align: center;
	}
	.div-title-right {
		width: 19%;
		height: auto;
		float: left;
	}
	.div-content {
		width: 100%;
		height: auto;
		margin: 0 auto;
		float: top;
		background-color: #E6E6FA; /* lavender */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	<!-- sub container, which will only go to 95% width -->
	<br><br><br>
	<div class="options">
	<p style="padding: 0; margin: 0; float: left;"><a href="{% url 'achiev:achiev_list' %}">&lt;back</a></p>
	<p style="padding: 0; margin: 0; float: right;"><a href="{% url 'achiev:achiev_edit' uid=achiev.unique_id %}">edit&gt;</a>
	</div>
	<br>
	<hr>
	<div class="container-sub">
		<!-- title goes here -->
		<div class="story-title">
			<div class="div-title-left">
				<h1>{{ achiev.name }}</h1>
			</div>
			<div class="div-title-right">
				<h2><em>{{ achiev.unique_id }}</em></h2>
			</div>
		</div>
		<div class="div-content">
			<q><strong><em>{{ achiev.in_game_description|linebreaks }}</em></strong></q>
			<hr>
			<p>{{ achiev.description|linebreaks }}</p>
		</div>
	</div>
</div>
{% endblock %}

mystek/achiev/templates/achiev/index.html
{% extends 'home/base.html' %}

{% block title %}Mystek - Achievement List{% endblock %}

{% block local_style %}
<style type="text/css">
	.container-main {
		width: 100%;
		height: 100%;
	}
	.div-logged-user-top {
		margin: 0 auto;
		float: top;
		width: 100%;
		height: auto;
	}
	.article-nav {
		list-style-type: none;
		margin: 0;
		padding: 0;
		overflow: hidden;
		background-color: #0000FF; /* blue */
		width: 100%;
		float: top;
	}
	.art-nav-item {
		display: block;
		color: white;
		text-align: center;
		padding: 14px 16px;
		text-decoration: none;
		margin: 0 auto;
		float: left;
		padding: 14px 16px;
	}
	.art-nav-item a {
		display: block;
		color: red;
		text-align: center;
		text-decoration: none;

	}
	.art-nav-item a:hover {
		background-color: #0000CC; /* darker blue */
	}
	.obj-container {
		margin: 0 auto;
		width: 95%;
		height: 70px;
		float: top;
		background-color: #DCDCDC; /* gainsboro */
		border: 1px solid black;
	}
	.obj-sub-left {
		margin: 0 auto;
		width: 80%;
		height: auto;
		float: left;
		background-color: #DCDCDC; /* gainsboro */
	}
	.obj-sub-right {
		margin: 0 auto;
		width: 20%;
		height: auto;
		float: right;
		overflow: auto;
		overflow-y: auto;
		background-color: #DCDCDC; /* gainsboro */
	}
</style>
{% endblock %}

{% block local_script %}
<script type="text/javascript"></script>
{% endblock %}

{# DEV_NOTES

# DJANGO_NOTES

#}

{% block content %}
<div class="container-main">
	{% if logged_in %}
	<br><br>
	<!-- DEV_NOTE:02 -->
	<!-- top div, which will allow for navigating to the write-article form -->
	<div class="div-logged-user-top">
		<ul class="article-nav">
			<li class="art-nav-item">Hello, {{ user.username }}</li>
			<li class="art-nav-item" style="float: right">
				<a href="{% url 'achiev:achiev_create' %}">
					Create Achievement
				</a>
			</li>
		</ul>
	</div>
	{% endif %}
	{% for achiev in objects_list %}
	<br>
	<div class="obj-container">
		<!-- 80% -->
		<div class="obj-sub-left">
			<h4>
				<!-- goto mystek.com/dashboard/story/<slug>/ -->
				<a href="{% url 'achiev:achiev_detail' uid=achiev.unique_id %}">
					{{ achiev.name }}
				</a>
			</h4>
			
		</div>
		<!-- 20% -->
		<div class="obj-sub-right">
			<h3><em>{{ achiev.unique_id }}</em></h3>
		</div>
	</div>
	<br>
	{% empty %}
	<br><br>
	<h1>Hey! There are no Achievements yet! :(</h1>
	<p>You can totally <a href="{% url 'achiev:achiev_create' %}">make</a> one, though. Like, finally, right? :D</p>
	{% endfor %}
</div>
{% endblock %}